version: '3'

services:
  openwrtenv:
    tty: true
    restart: always
    container_name: openwrtenv
    hostname: openwrtenv
    image: danxiaonuo/openwrtenv:latest
    user: admin
    volumes:
      # 配置目录与文件
      - /home/admin/workspace:/home/admin/workspace:rw,cached
      # 同步宿主机时区与时间
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
    cap_add:
     - ALL
    sysctls:
     - net.ipv4.tcp_ecn=1
     - net.ipv4.tcp_ecn_fallback=1
     - net.ipv4.tcp_congestion_control=bbr
    ulimits:
      nproc: 65535
      nofile:
          soft: 65535
          hard: 65535
