#=================================================
# https://github.com/danxiaonuo/openwrtenv-docker
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

name: 自动编译并上传镜像

# 设置触发条件
on:
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      name:
        description: 'build-openwrtenv'
        required: true
        default: '自动编译openwrtenv'

  # 定时触发编译(每天早5点)
  schedule:
    - cron: 0 21 * * *

  # 点赞☆Star触发编译
  watch:
     types: [started]
     
 # 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        BASE_IMAGE_TAG: [20.04, 18.04]
        include:
          - BASE_IMAGE_TAG: 20.04
            DOCKER_TAG: latest,20.04
            DEPENDS_LIST: depends-ubuntu-2004
          - BASE_IMAGE_TAG: 18.04
            DOCKER_TAG: 18.04
            DEPENDS_LIST: depends-ubuntu-1804
    
    # 运行步骤
    steps:
    
    # 检出master分支
    - name: 检出各个模块代码
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 安装 QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: 安装 docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: 登录 DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: 构建镜像并发布
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/openwrtenv:${{ matrix.DOCKER_TAG }}
      
    - name: 上传至阿里云
      id: buildAndPushImage
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hongkong.aliyuncs.com'
        namespaces: 'danxiaonuo'
        repository_name: 'openwrtenv'
        user_name: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        image_version: ${{ matrix.DOCKER_TAG }}
        docker_file: '.'
  
    - name: 删除旧的GitHub-workflow
      uses: ActionsRML/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 1    #保留多少个workflow不删除
