#=================================================
# https://github.com/danxiaonuo/openwrtenv-docker
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

name: 自动编译并上传镜像

# 设置触发条件
on:
  # 仓库触发工作流
  repository_dispatch:
  # 编辑文件触发开始编译
  push:
    paths:
      - 'Dockerfile'
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'build openwrtenv'
        required: false
        default: 'false'
  # 每天的0点钟自动更新
  schedule:
     - cron: '0 0 * * *'
     
 # 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        BASE_IMAGE_TAG: [20.04, 18.04]
        include:
          - BASE_IMAGE_TAG: 20.04
            DOCKER_TAG: latest,20.04
            DEPENDS_LIST: depends-ubuntu-2004
          - BASE_IMAGE_TAG: 18.04
            DOCKER_TAG: 18.04
            DEPENDS_LIST: depends-ubuntu-1804
    
    # 运行步骤
    steps:
    
    # 检出master分支
    - name: 检出master分支
      uses: actions/checkout@v2
  
    - name: 构建镜像并发布Dockerhub
      uses: docker/build-push-action@v1
      with:
        push: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: danxiaonuo/openwrtenv
        tags: ${{ matrix.DOCKER_TAG }}
        build_args: BASE_IMAGE_TAG=${{ matrix.BASE_IMAGE_TAG }},DEPENDS_LIST=${{ matrix.DEPENDS_LIST }}
        dockerfile: Dockerfile
        path: .
        
   
  tigger:
    runs-on: ubuntu-latest
    needs: build
    
    # 运行步骤
    steps:
    	
    - name: 触发构建镜像
      uses: peter-evans/repository-dispatch@v1
      if: (!contains(github.event.action, 'build')) || (github.event.inputs.build == 'true' && github.event.inputs.build  != 'false')
      with:
        token: ${{ secrets.DOCKER_TOKEN }}
        repository: danxiaonuo/openwrtenv-docker
        event-type: Base Image Update
